### ISSUE TITLE
The manifests are not updated 

### ISSUE THREAD

**Issue by mart3051** [microsoft/sqlworkshops-sqlonopenshift#2]
The manifests are not up to date .
The Deployments are being referred from 
apiVersion: apps/v1beta1
Which should be updated to 
apiVersion: apps/v1 to support 4.x of Openshift.

Also the operator does not work for 4.x, can it be made compatible with 4.x

**Comment by rgward** [comment]
This course had not been updated for some time because it was based on OpenShift 3.11 and SQL Server 2019 preview releases. Everything is now updated for SQL Server 2019 GA images based on RHEL 8, OpenShift 4, and apiVersion changes required for v1
